echo "apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-deployment
spec:
  selector:
    matchLabels:
      app: ubuntu-deployment
  template:
    metadata:
      labels:
        app: ubuntu-deployment
    spec:
      containers:
      - name: ubuntu-deployment
        image: ubuntu
        command:
        - /bin/bash
        - "-c"
        - "sleep 60m"
        volumeMounts:
        - mountPath: /data
          name: ssd10g
      volumes:
        - name: ssd10g
          persistentVolumeClaim:
            claimName: gcp-pvc" | kubectl apply -f -
